apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-cluster-zookeeper-2
  labels:
    app: kafka
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  nfs:
    path: /mnt/data/152/k8s/cluster/zookeeper  # NFS共享的路径
    server: 192.168.2.160  # NFS服务器地址
